name: "Release Workbench Dev Container Images"

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish `workbench-rust` Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/with-caer/workbench-rust
          cacheFrom: ghcr.io/with-caer/workbench-rust
          push: always
          subFolder: devcontainers/workbench-rust
